# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  - task: SonarQubePrepare@5
    inputs:
      SonarQube: 'SonarQube_ADD_manual'
      scannerMode: 'MSBuild'
      projectKey: 'Azure-Devops'
      projectName: 'Azure-Devops'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
